[features]
seeds = false
skip-lint = false
[programs.localnet]
posts = "8DCPDL7UJeWe9JtQ3QCf5E4dbngzZwZ7h1RrKbdHdVYm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/rayturla/.config/solana/id-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
